spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: poc

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer